spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: netty-server
          uri: lb:ws://Chat-Netty-Server
          predicates:
            - Path=/chat-netty-server/**
          filters:
            - StripPrefix=1
ignoreUrls: /chat-netty-server/**