server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: springcloud-stream-kafka-provider
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        kafka-out-0:
          destination: TEST_TOPIC
          group: TEST_GROUP
          contentType: text/plain
#          partition-count: 2